# This is a basic workflow to help you get started with Actions

name: Linux_Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  QT_VERSION: 5.12.8

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Add Boost
        run: sudo add-apt-repository ppa:mhier/libboost-latest && sudo apt-get update
      
      - name: Install Dependencies
        run: sudo apt install libboost1.74-dev libssl-dev qt5-qmake libstdc++-8-dev

      # Runs a set of commands using the runners shell
      - name: QMake project Debug
        shell: bash
        run: qmake -qt=qt5 libhttp.pro -spec linux-clang CONFIG+=qml_debug CONFIG+=qtquickcompiler CONFIG+=force_debug_info CONFIG+=separate_debug_info CONFIG+=debug && /usr/bin/make qmake_all

      - name: Make clean 
        shell: bash
        run: make clean -j8

      - name: Make
        shell: bash
        run: make -j8
      
      - name: QMake project Release
        shell: bash
        run: qmake -qt=qt5 libhttp.pro -spec linux-clang CONFIG+=qtquickcompiler && /usr/bin/make qmake_all

      - name: Make clean 
        shell: bash
        run: make clean -j8

      - name: Make
        shell: bash
        run: make -j8
